name 'blankone'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures blankone'
long_description 'Installs/Configures blankone'
version '0.1.0'
